from script.base_api.service_crm.school import *
from script.base_api.service_crm.back_clue import *
from script.base_api.service_crm.systemMessage import *
from script.base_api.service_crm.document import *
from script.base_api.service_crm.lost_communicate_record import *
from script.base_api.service_crm.enum import *
from script.base_api.service_crm.crm import *
from script.base_api.service_crm.dict import *
from script.base_api.service_crm.direct import *
from script.base_api.service_crm.clue import *
from script.base_api.service_crm.communicate import *
from script.base_api.service_crm.lostWarning import *
from script.base_api.service_crm.staging import *
from script.base_api.service_crm.customMessage import *
from script.base_api.service_crm.documentTag import *
from script.base_api.service_crm.agency import *
from script.base_api.service_crm.documentDirectory import *
from script.base_api.service_crm.lostStudent import *
from script.base_api.service_crm.systemMessageItem import *
from script.base_api.service_crm.customMessageItem import *
from script.base_api.service_crm.documentRecord import *
