from script.base_api.service_crm.document_temp import *
from script.base_api.service_crm.documentDirectory_temp import *
from script.base_api.service_crm.school_temp import *
from script.base_api.service_crm.dict_temp import *
from script.base_api.service_crm.lostStudent_temp import *
from script.base_api.service_crm.systemMessageItem_temp import *
from script.base_api.service_crm.documentRecord_temp import *
from script.base_api.service_crm.systemMessage_temp import *
from script.base_api.service_crm.communicate_temp import *
from script.base_api.service_crm.back_clue_temp import *
from script.base_api.service_crm.staging_temp import *
from script.base_api.service_crm.direct_temp import *
from script.base_api.service_crm.lost_communicate_record_temp import *
from script.base_api.service_crm.agency_temp import *
from script.base_api.service_crm.customMessageItem_temp import *
from script.base_api.service_crm.clue_temp import *
from script.base_api.service_crm.lostWarning_temp import *
from script.base_api.service_crm.documentTag_temp import *
from script.base_api.service_crm.crm_temp import *
from script.base_api.service_crm.enum_temp import *
from script.base_api.service_crm.customMessage_temp import *
