from script.base_api.service_education.system_temp import *
from script.base_api.service_education.batchClass_temp import *
from script.base_api.service_education.classCapacity_temp import *
from script.base_api.service_education.batch_temp import *
from script.base_api.service_education.education_temp import *
from script.base_api.service_education.classDirector_temp import *
from script.base_api.service_education.jst_home_temp import *
from script.base_api.service_education.classes_temp import *
from script.base_api.service_education.app_temp import *
from script.base_api.service_education.jst_app_temp import *
