from script.base_api.service_education.app import *
from script.base_api.service_education.batch import *
from script.base_api.service_education.jst_home import *
from script.base_api.service_education.system import *
from script.base_api.service_education.classes import *
from script.base_api.service_education.batchClass import *
from script.base_api.service_education.jst_app import *
from script.base_api.service_education.classCapacity import *
from script.base_api.service_education.education import *
from script.base_api.service_education.classDirector import *
