from script.base_api.service_gos.shareEvent import *
from script.base_api.service_gos.group import *
from script.base_api.service_gos.package import *
from script.base_api.service_gos.gos import *
from script.base_api.service_gos.api import *
from script.base_api.service_gos.diagnosis import *
from script.base_api.service_gos.banner import *
from script.base_api.service_gos.gos_api import *
from script.base_api.service_gos.applet import *
from script.base_api.service_gos.carousel import *
from script.base_api.service_gos.goods import *
