from script.base_api.service_gos.gos_api_temp import *
from script.base_api.service_gos.applet_temp import *
from script.base_api.service_gos.goods_temp import *
from script.base_api.service_gos.shareEvent_temp import *
from script.base_api.service_gos.api_temp import *
from script.base_api.service_gos.group_temp import *
from script.base_api.service_gos.package_temp import *
from script.base_api.service_gos.diagnosis_temp import *
from script.base_api.service_gos.banner_temp import *
from script.base_api.service_gos.gos_temp import *
from script.base_api.service_gos.carousel_temp import *
