from script.base_api.service_profile import *
from script.base_api.api_periodical import *
from script.base_api.service_statistics import *
from script.base_api.service_gos import *
from script.base_api.service_descartes import *
from script.base_api.api_teach_web import *
from script.base_api.service_public import *
from script.base_api.service_order import *
from script.base_api.service_question import *
from script.base_api.api_research_web import *
from script.base_api.service_science import *
from script.base_api.api_jksxb_mini import *
from script.base_api.service_report import *
from script.base_api.service_education import *
from script.base_api.api_operation_web import *
from script.base_api.service_idea import *
from script.base_api.api_operation_app import *
from script.base_api.service_pay import *
from script.base_api.service_identity import *
from script.base_api.service_finance import *
from script.base_api.service_research import *
from script.base_api.service_src import *
from script.base_api.api_admin import *
from script.base_api.service_crm import *
from script.base_api.service_user import *
from script.base_api.api_jksxb_app import *
from script.base_api.service_statistics_metrics import *
from script.base_api.service_pigeon import *
