from script.base_api.api_operation_web.report_temp import *
from script.base_api.api_operation_web.introduce_temp import *
from script.base_api.api_operation_web.ruleSetting_temp import *
from script.base_api.api_operation_web.versionInfo_temp import *
from script.base_api.api_operation_web.charge_temp import *
from script.base_api.api_operation_web.export_temp import *
from script.base_api.api_operation_web.banner_temp import *
from script.base_api.api_operation_web.coupon_temp import *
from script.base_api.api_operation_web.big_screen_temp import *
from script.base_api.api_operation_web.discount_temp import *
from script.base_api.api_operation_web.expense_temp import *
from script.base_api.api_operation_web.orderFlow_temp import *
from script.base_api.api_operation_web.pay_temp import *
from script.base_api.api_operation_web.renewal_temp import *
from script.base_api.api_operation_web.order_temp import *
from script.base_api.api_operation_web.share_temp import *
