from script.base_api.api_jksxb_mini.coupon import *
from script.base_api.api_jksxb_mini.user import *
from script.base_api.api_jksxb_mini.idea import *
from script.base_api.api_jksxb_mini.goods import *
from script.base_api.api_jksxb_mini.banner import *
from script.base_api.api_jksxb_mini.pay import *
from script.base_api.api_jksxb_mini.share import *
from script.base_api.api_jksxb_mini.productExamination import *
from script.base_api.api_jksxb_mini.orderFlow import *
from script.base_api.api_jksxb_mini.order import *
from script.base_api.api_jksxb_mini.zan import *
from script.base_api.api_jksxb_mini.buryData import *
from script.base_api.api_jksxb_mini.versionInfo import *
