from script.base_api.api_jksxb_mini.goods_temp import *
from script.base_api.api_jksxb_mini.zan_temp import *
from script.base_api.api_jksxb_mini.versionInfo_temp import *
from script.base_api.api_jksxb_mini.banner_temp import *
from script.base_api.api_jksxb_mini.coupon_temp import *
from script.base_api.api_jksxb_mini.productExamination_temp import *
from script.base_api.api_jksxb_mini.orderFlow_temp import *
from script.base_api.api_jksxb_mini.buryData_temp import *
from script.base_api.api_jksxb_mini.user_temp import *
from script.base_api.api_jksxb_mini.idea_temp import *
from script.base_api.api_jksxb_mini.pay_temp import *
from script.base_api.api_jksxb_mini.order_temp import *
from script.base_api.api_jksxb_mini.share_temp import *
