from script.base_api.service_public.qrcode_temp import *
from script.base_api.service_public.check_recommit_temp import *
from script.base_api.service_public.backup_temp import *
from script.base_api.service_public.schools_temp import *
from script.base_api.service_public.systemSetting_temp import *
from script.base_api.service_public.entranceExam_temp import *
from script.base_api.service_public.version_temp import *
from script.base_api.service_public.finance_temp import *
from script.base_api.service_public.upload_temp import *
from script.base_api.service_public.customHeader_temp import *
from script.base_api.service_public.preview_temp import *
from script.base_api.service_public.app_temp import *
from script.base_api.service_public.vod_temp import *
from script.base_api.service_public.export_temp import *
from script.base_api.service_public.api_temp import *
from script.base_api.service_public.targets_temp import *
from script.base_api.service_public.jst_app_temp import *
from script.base_api.service_public.src_temp import *
from script.base_api.service_public.notices_temp import *
from script.base_api.service_public.baseParam_temp import *
from script.base_api.service_public.notice_temp import *
from script.base_api.service_public.cos_temp import *
from script.base_api.service_public.resource_temp import *
