from script.base_api.service_public.vod import *
from script.base_api.service_public.cos import *
from script.base_api.service_public.notice import *
from script.base_api.service_public.check_recommit import *
from script.base_api.service_public.api import *
from script.base_api.service_public.targets import *
from script.base_api.service_public.baseParam import *
from script.base_api.service_public.finance import *
from script.base_api.service_public.resource import *
from script.base_api.service_public.backup import *
from script.base_api.service_public.notices import *
from script.base_api.service_public.systemSetting import *
from script.base_api.service_public.version import *
from script.base_api.service_public.customHeader import *
from script.base_api.service_public.src import *
from script.base_api.service_public.preview import *
from script.base_api.service_public.app import *
from script.base_api.service_public.export import *
from script.base_api.service_public.schools import *
from script.base_api.service_public.upload import *
from script.base_api.service_public.entranceExam import *
from script.base_api.service_public.jst_app import *
from script.base_api.service_public.qrcode import *
