from script.base_api.api_jksxb_app.coupon import *
from script.base_api.api_jksxb_app.app import *
from script.base_api.api_jksxb_app.playVideo import *
from script.base_api.api_jksxb_app.coursePreview import *
from script.base_api.api_jksxb_app.orderFlow import *
from script.base_api.api_jksxb_app.pay import *
from script.base_api.api_jksxb_app.homework import *
from script.base_api.api_jksxb_app.banner import *
from script.base_api.api_jksxb_app.order import *
