from script.base_api.api_jksxb_app.homework_temp import *
from script.base_api.api_jksxb_app.app_temp import *
from script.base_api.api_jksxb_app.coupon_temp import *
from script.base_api.api_jksxb_app.banner_temp import *
from script.base_api.api_jksxb_app.orderFlow_temp import *
from script.base_api.api_jksxb_app.playVideo_temp import *
from script.base_api.api_jksxb_app.pay_temp import *
from script.base_api.api_jksxb_app.order_temp import *
from script.base_api.api_jksxb_app.coursePreview_temp import *
