from script.base_api.service_profile.coupon import *
from script.base_api.service_profile.student import *
from script.base_api.service_profile.classes import *
from script.base_api.service_profile.videoPlayAddress import *
from script.base_api.service_profile.classHourChange import *
from script.base_api.service_profile.jst_app import *
from script.base_api.service_profile.pushRelationship import *
from script.base_api.service_profile.feedback import *
from script.base_api.service_profile.applet import *
from script.base_api.service_profile.studtent import *
from script.base_api.service_profile.teachers import *
from script.base_api.service_profile.transfer_records import *
from script.base_api.service_profile.external import *
from script.base_api.service_profile.manualSchedule import *
from script.base_api.service_profile.memberships import *
from script.base_api.service_profile.homework import *
from script.base_api.service_profile.courseNote import *
from script.base_api.service_profile.feedbackType import *
from script.base_api.service_profile.app import *
from script.base_api.service_profile.class_ import *
from script.base_api.service_profile.attendances import *
from script.base_api.service_profile.public import *
from script.base_api.service_profile.course_notes import *
from script.base_api.service_profile.classfeedback import *
from script.base_api.service_profile.login import *
from script.base_api.service_profile.classChange import *
from script.base_api.service_profile.schedules import *
from script.base_api.service_profile.purchaseOrder import *
from script.base_api.service_profile.geekPreviewReport import *
from script.base_api.service_profile.transferred import *
from script.base_api.service_profile.plaso import *
from script.base_api.service_profile.performances import *
from script.base_api.service_profile.user import *
from script.base_api.service_profile.api import *
from script.base_api.service_profile.userCheckpoint import *
from script.base_api.service_profile.students import *
from script.base_api.service_profile.finance import *
from script.base_api.service_profile.parent import *
