from script.base_api.service_question.exam_temp import *
from script.base_api.service_question.examination_temp import *
from script.base_api.service_question.materialContribution_temp import *
from script.base_api.service_question.jst_temp import *
from script.base_api.service_question.question_jst_temp import *
from script.base_api.service_question.question_video_temp import *
from script.base_api.service_question.question_bank_temp import *
from script.base_api.service_question.basic_training_temp import *
from script.base_api.service_question.monthExamination_temp import *
from script.base_api.service_question.questionMaterial_temp import *
from script.base_api.service_question.question_source_temp import *
from script.base_api.service_question.online_temp import *
from script.base_api.service_question.chapter_tree_temp import *
from script.base_api.service_question.admission_temp import *
