from script.base_api.service_question.question_bank import *
from script.base_api.service_question.questionMaterial import *
from script.base_api.service_question.online import *
from script.base_api.service_question.basic_training import *
from script.base_api.service_question.admission import *
from script.base_api.service_question.examination import *
from script.base_api.service_question.materialContribution import *
from script.base_api.service_question.monthExamination import *
from script.base_api.service_question.jst import *
from script.base_api.service_question.question_jst import *
from script.base_api.service_question.chapter_tree import *
from script.base_api.service_question.question_video import *
from script.base_api.service_question.exam import *
from script.base_api.service_question.question_source import *
