from script.base_api.service_research.preview import *
from script.base_api.service_research.teaching_plan import *
from script.base_api.service_research.teaching_plans import *
from script.base_api.service_research.examination import *
from script.base_api.service_research.prepar import *
from script.base_api.service_research.prepareLessons import *
from script.base_api.service_research.periodical import *
from script.base_api.service_research.jst_app import *
from script.base_api.service_research.teaching_exercises import *
from script.base_api.service_research.teaching_exercise import *
from script.base_api.service_research.video import *
from script.base_api.service_research.dowLogController import *
from script.base_api.service_research.attendClass import *
from script.base_api.service_research.courseWareScoreController import *
from script.base_api.service_research.question_bank import *
from script.base_api.service_research.courseWareEvaluateController import *
from script.base_api.service_research.api import *
from script.base_api.service_research.cloudDiskController import *
from script.base_api.service_research.research import *
