from script.base_api.service_research.prepareLessons_temp import *
from script.base_api.service_research.examination_temp import *
from script.base_api.service_research.research_temp import *
from script.base_api.service_research.periodical_temp import *
from script.base_api.service_research.question_bank_temp import *
from script.base_api.service_research.dowLogController_temp import *
from script.base_api.service_research.courseWareEvaluateController_temp import *
from script.base_api.service_research.preview_temp import *
from script.base_api.service_research.attendClass_temp import *
from script.base_api.service_research.courseWareScoreController_temp import *
from script.base_api.service_research.api_temp import *
from script.base_api.service_research.teaching_exercise_temp import *
from script.base_api.service_research.jst_app_temp import *
from script.base_api.service_research.prepar_temp import *
from script.base_api.service_research.video_temp import *
from script.base_api.service_research.teaching_plan_temp import *
from script.base_api.service_research.teaching_plans_temp import *
from script.base_api.service_research.teaching_exercises_temp import *
from script.base_api.service_research.cloudDiskController_temp import *
